FROM ubuntu:18.04
RUN sed -i s:/archive.ubuntu.com:/mirrors.tuna.tsinghua.edu.cn/ubuntu:g /etc/apt/sources.list
RUN cat /etc/apt/sources.list
RUN apt-get clean
RUN apt-get -y update --fix-missing

RUN apt-get update && apt-get install -y \
    libx11-6 libgomp1 python3

COPY lib /usr/lib/

COPY bin /usr/bin/

COPY pylib /usr/lib/python3/dist-packages/
